#14.6 在goroutine中使用recover
一个使用recover的应用(参见13.3节)是在一个服务器内部关闭一个失败的goroutine而不影响到其它正在运行的goroutine.

	func server(workChan <-chan *Work) {
		for work := range workChan {
			go safelyDo(work)	// start the goroutine for that work
		}
	}

	func safelyDo(work *Work) {
		defer func() {
			if err := recover(); err != nil {
				log.Printf("work failed with %s in %v:", err, work)
			}
		}()
		do(work)
	}

在上面的代码片段中,如果do(work) panic了,错误将会被记录并且goroutine会干净的退出而不影响到其他goroutine.

	
##链接
- [目录](directory.md)
- 上一节：[](14.5.md)
- 下一节：[](14.7.md)